# Generated by Django 5.2.1 on 2025-07-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='lectureslot',
            unique_together={('subject', 'teacher', 'day_of_week', 'lecture_number')},
        ),
    ]
