# Generated by Django 5.2.1 on 2025-07-21 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('timetable', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lecture_number', models.PositiveIntegerField(editable=False)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lectureslot')),
                ('subject', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile')),
            ],
            options={
                'ordering': ['date', 'lecture_number'],
                'unique_together': {('slot', 'date')},
            },
        ),
    ]
