# Generated by Django 5.2.1 on 2025-07-22 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_scheduledlecture'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledlecture',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_lectures', to='users.teacherprofile'),
        ),
    ]
