# Generated by Django 5.2.1 on 2025-07-22 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('timetable', '0004_scheduledlecture_substitute_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledlecture',
            name='substitute_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_subjects', to='academics.subject'),
        ),
    ]
