# Generated by Django 5.2.1 on 2025-07-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_scheduledlecture_substitute_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectureslot',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='lectureslot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lectureslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lectureslot',
            name='start_time',
        ),
    ]
