# Generated by Django 5.2.1 on 2025-08-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_studentgroup_section'),
        ('timetable', '0006_alter_lectureslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureslot',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.studentgroup'),
        ),
        migrations.AddField(
            model_name='lectureslot',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.section'),
        ),
        migrations.AddField(
            model_name='scheduledlecture',
            name='group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.studentgroup'),
        ),
        migrations.AddField(
            model_name='scheduledlecture',
            name='section',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.section'),
        ),
    ]
