# Generated by Django 5.2.1 on 2025-08-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_section_studentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.section'),
        ),
    ]
