# Generated by Django 5.2.1 on 2025-07-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
        ('timetable', '0003_scheduledlecture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['lecture__date', 'lecture__slot__lecture_number']},
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='session',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='timetable.scheduledlecture'),
        ),
    ]
